# Generated by Django 3.2.23 on 2023-11-19 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="staus",
            new_name="status",
        ),
    ]
